version: 2
jobs:
  build:
  
    docker:    
      - image: circleci/postgres:10-alpine-postgis-ram
      - image: circleci/node:lts
        environment:
          TEST_DATABASE_URL: postgresql://root@localhost/circle_test
        
    steps:
      - checkout
      - run: sudo apt install postgresql-client-10
      - run:
          name: test
          command: psql -d $TEST_DATABASE_URL -f schema.sql
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test-results.xml