version: 2
jobs:
  build:
  
    docker:    
      - image: circleci/postgres:11-alpine-postgis-ram
        environment:
          TEST_DATABASE_URL: postgresql://root@localhost/circle_test
      - image: circleci/postgres:11-alpine-postgis-ram

        
    steps:
      - checkout
      - run: apk add postgresql-client
      - run:
          name: test
          command: psql -d $TEST_DATABASE_URL -f schema.sql
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test-results.xml